export const products = [
  {
    id: 1,
    name: 'Pixel 8a',
    category: 'phone',
    price: 499,
    description: 'Mid-range Android phone with excellent camera and clean software.',
    tags: ['android', 'camera', 'budget'],
  },
  {
    id: 2,
    name: 'iPhone 15',
    category: 'phone',
    price: 799,
    description: 'Apple flagship with USB-C, great performance, and iOS ecosystem.',
    tags: ['ios', 'premium', 'camera'],
  },
  {
    id: 3,
    name: 'Samsung Galaxy S24',
    category: 'phone',
    price: 899,
    description: 'Premium Android flagship with bright display and AI features.',
    tags: ['android', 'premium', 'display'],
  },
  {
    id: 4,
    name: 'Motorola Moto G Power',
    category: 'phone',
    price: 299,
    description: 'Affordable phone with long battery life for everyday use.',
    tags: ['android', 'budget', 'battery'],
  },
  {
    id: 5,
    name: 'MacBook Air M3',
    category: 'laptop',
    price: 1099,
    description: 'Lightweight laptop with Apple Silicon for students and professionals.',
    tags: ['macos', 'portable', 'premium'],
  },
  {
    id: 6,
    name: 'Dell XPS 13',
    category: 'laptop',
    price: 999,
    description: 'Compact Windows ultrabook with premium build quality.',
    tags: ['windows', 'portable', 'business'],
  },
  {
    id: 7,
    name: 'Lenovo IdeaPad 3',
    category: 'laptop',
    price: 449,
    description: 'Budget-friendly laptop for browsing, school, and light work.',
    tags: ['windows', 'budget', 'student'],
  },
  {
    id: 8,
    name: 'ASUS ROG Zephyrus G14',
    category: 'laptop',
    price: 1499,
    description: 'Powerful gaming laptop with dedicated GPU and fast refresh display.',
    tags: ['windows', 'gaming', 'performance'],
  },
  {
    id: 9,
    name: 'Sony WH-1000XM5',
    category: 'headphones',
    price: 349,
    description: 'Industry-leading noise-canceling over-ear headphones.',
    tags: ['audio', 'noise-canceling', 'travel'],
  },
  {
    id: 10,
    name: 'AirPods Pro 2',
    category: 'headphones',
    price: 249,
    description: 'Compact wireless earbuds with active noise cancellation.',
    tags: ['audio', 'wireless', 'apple'],
  },
  {
    id: 11,
    name: 'JBL Tune 510BT',
    category: 'headphones',
    price: 49,
    description: 'Affordable Bluetooth on-ear headphones for casual listening.',
    tags: ['audio', 'budget', 'wireless'],
  },
  {
    id: 12,
    name: 'iPad Air',
    category: 'tablet',
    price: 599,
    description: 'Versatile tablet for drawing, reading, and productivity.',
    tags: ['apple', 'tablet', 'creative'],
  },
  {
    id: 13,
    name: 'Samsung Galaxy Tab A9',
    category: 'tablet',
    price: 219,
    description: 'Entry-level Android tablet for media and light tasks.',
    tags: ['android', 'budget', 'tablet'],
  },
  {
    id: 14,
    name: 'Apple Watch SE',
    category: 'watch',
    price: 249,
    description: 'Fitness-focused smartwatch with core Apple Watch features.',
    tags: ['apple', 'fitness', 'wearable'],
  },
  {
    id: 15,
    name: 'Fitbit Charge 6',
    category: 'watch',
    price: 159,
    description: 'Fitness tracker with heart rate monitoring and sleep tracking.',
    tags: ['fitness', 'budget', 'wearable'],
  },
];
